# -*- coding: utf-8 -*-
"""cvLab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xwSU4X8v5p8p53H-dYezIVjoRjByTZc
"""

import cv2
import matplotlib.pyplot as plt

def show_image_slicing(image_path):
  img = cv2.imread(image_path, 0)
  if img is None:
    print(f"Error: Could not load image from {image_path}")
    return

  rmin = 100
  rmax = 200

  slicing_wo_background = np.zeros(img.shape, dtype=np.uint8)
  slicing_w_background = np.copy(img)
  for i in range(img.shape[0]):
    for j in range(img.shape[1]):
      pixel_value = img[i][j]
      if rmin <= pixel_value <= rmax:
        slicing_wo_background[i][j] = 255
        slicing_w_background[i][j] = 255


  plt.figure(figsize=(15, 5))

  plt.subplot(1, 3, 1)
  plt.imshow(img, cmap='gray')
  plt.title('Original Image')
  plt.axis('off')

  plt.subplot(1, 3, 2)
  plt.imshow(slicing_wo_background, cmap='gray')
  plt.title('Slicing w/o Background (in range = 255)')
  plt.axis('off')

  plt.subplot(1, 3, 3)
  plt.imshow(slicing_w_background, cmap='gray')
  plt.title('Slicing with Background (in range = 255, else original)')
  plt.axis('off')

  plt.show()
show_image_slicing('/content/21.jpg')